<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="20222" started-at="2020-07-03T21:04:27Z" finished-at="2020-07-03T21:04:47Z">
    <groups>
      <group name="regression">
        <method signature="OnlyWomenFirstTests.verify_women_test()[pri:1, instance:com.testing.headerPage.testCases.OnlyWomenFirstTests@8b87145]" name="verify_women_test" class="com.testing.headerPage.testCases.OnlyWomenFirstTests"/>
      </group> <!-- regression -->
    </groups>
    <test name="Default test" duration-ms="20222" started-at="2020-07-03T21:04:27Z" finished-at="2020-07-03T21:04:47Z">
      <class name="com.testing.headerPage.testCases.OnlyWomenFirstTests">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.testing.headerPage.testCases.OnlyWomenFirstTests@8b87145]" name="setUp" is-config="true" duration-ms="14565" started-at="2020-07-03T21:04:27Z" finished-at="2020-07-03T21:04:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="verify_women_test()[pri:1, instance:com.testing.headerPage.testCases.OnlyWomenFirstTests@8b87145]" name="verify_women_test" duration-ms="5604" started-at="2020-07-03T21:04:41Z" finished-at="2020-07-03T21:04:47Z">
          <exception class="java.lang.NumberFormatException">
            <message>
              <![CDATA[For input string: "01,079"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NumberFormatException: For input string: "01,079"
at java.lang.NumberFormatException.forInputString(Unknown Source)
at java.lang.Integer.parseInt(Unknown Source)
at java.lang.Integer.valueOf(Unknown Source)
at com.testing.headerPage.testCases.OnlyWomenFirstTests.verify_women_test(OnlyWomenFirstTests.java:68)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NumberFormatException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_women_test -->
      </class> <!-- com.testing.headerPage.testCases.OnlyWomenFirstTests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
